### ISSUE TITLE
Focus / Open menu button in response to keyboard shortcut

### ISSUE THREAD

**Issue by pcj** [google/closure-library#1011]
I am implementing functionality similar to google docs menu etc wherein I have a menuBar with a list of `goog.ui.Menu`s & associated `goog.ui.MenuButton`s.  

I have a keyboard shortcut for `alt+f` that (currently) triggers `menuButton.setOpen(true)`. 

Although this *does* show the menu, the focus is not quite correct as the ENTER, SPACE, LEFT, RIGHT keys don't have an effect at this point.  Conversely, If I mouseover and click the menuButton, these keys do work as expected.

So, what is the correct way to implement this type of behavior?  How do I correctly allow the user to ctrl-f the File menu and allow them to not have to use the mouse?  Thanks in advance!

**Comment by kjin** [comment]
Internal issue http://b/147282551 created.

**Comment by kjin** [comment]
I'm not very familiar with the goog.ui library, but looking at what `goog.ui.MenuButton.handleMouseDown` does besides call `setOpen(true)`, I see that it also activates the control and focuses its key event target:

https://github.com/google/closure-library/blob/36d2c6df96b21043361b3bca4b7b5e981cb91471/closure/goog/ui/control.js#L1291-L1298

So while I can't advise on whether there is a more correct way is to do this, it seems that it's at minimum necessary to call `getKeyEventTarget().focus()` (and probably `setActive()` too, just to keep things consistent with what happens when you click the button). Given that `getKeyEventTarget().focus()` isn't called from any other handler, I'm not sure if there is any other function you could call that encapsulates this.

**Comment by pcj** [comment]
Thanks @kjin I tried a bunch of different combinations without success, let me try the combination of `.focus()` and `.setActive()`

**Comment by shicks** [comment]
@pcj is this resolved?  If so, please close.  If not, please add more information.  Thanks!

**Comment by pcj** [comment]
I seem to have it working via:

```
      button.setOpen(true);
      button.getElementStrict().parentElement.focus();
      button.setActive(true);
```

That is probably not the minimal combination but I since moved on and have not tried to optimize it further.
