### ISSUE TITLE
Consolidate UA utils

### ISSUE THREAD

**Issue by ghost** [google/closure-library#1061]
There are currently multiple utils for user agent detection: goog.useragent, and the one in goog.labs.

They can be consolidated to provide users a single consolidated API.

**Comment by shicks** [comment]
The problem here is that there are some slight differences in how the two libraries work - they're not quite drop-in compatible with each other.

I think the first order of business is to determine what functionality the labs version may be missing from the original one, fill it in, and then we can deprecate the original library in good conscience.

**Comment by max19931** [comment]
Why not remove them completely as client side User Agent spoofing via an Addon is very easy?

But Browser Feature detection is either feature is supported natively or it needs to be polyfilled to have Support.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
