### ISSUE TITLE
`goog.Uri.getPath` returns partially decoded value

### ISSUE THREAD

**Issue by p-himik** [google/closure-library#1083]
```js
(new goog.Uri('http://example.com/%25_%5C')).getPath()
=> "/%25_\"
```
I would expect either `"/%25_%5C"` or `"%_\"`, but not something in between.

**Comment by 12wrigja** [comment]
In general I'd encourage you to use the new [URL module](https://github.com/google/closure-library/blob/master/closure/goog/url/url.js) if possible.

It seems that this is because %25 is considered a reserved character (although it's not listed as such in the relevant RFC). I think all the get* methods might be missing calls to removeDoubleEncoding_ that would fix this.

**Comment by shicks** [comment]
Given that goog.url handles this correctly and is encouraged for most use cases, this doesn't seem likely that we're going to get to this.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
