### ISSUE TITLE
goog.date.UtcDateTime/fromIsoString parses 0001 as 1901 (breaking change/bug?)

### ISSUE THREAD

**Issue by Frozenlock** [google/closure-library#1089]
I haven't seen anything related in the release notes, so I open this issue in case the behavior is unintended.

I'm upgrading from an earlier version. (20170809)
Back then `goog.date.UtcDateTime/fromIsoString` would parse `0001-05-08T12:30:15.181Z` as being the year 1.

However now it would parse it as being the year 1901.

While [years before 1583](https://en.wikipedia.org/wiki/ISO_8601#Years) are not a requirement by ISO8601, I would expect the parsing to return either null or the correct year.

**Comment by Frozenlock** [comment]
FWIW, the old behavior was still in version 20190213.

**Comment by Elias-0001** [comment]
:O

**Comment by kjin** [comment]
@Frozenlock thanks for filing this and sorry for the late response. I think this is due to e6a8908, which uses `Date.UTC` as part of parsing, but only if the string to be parsed contains a timezone. `Date.UTC` turns years 0-99 to 1900-1999 (as documented [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/UTC#description)), so we end up passing along that behavior as well.

We'll have the function return `null` (indicating that the string can't be parsed). I looked into using `setFullYear` to set a year to 0-99 as per [this StackOverflow post](https://stackoverflow.com/a/7766188), but this results in extra complexity and possible subtly incorrect results, both of which I feel like is unwarranted for an unsupported date range as you mentioned.

**Comment by kjin** [comment]
@Frozenlock This has been landed, but I just remembered that we actually opted to support years 0-99 rather than returning `null`. I've edited my previous post to reflect this.
