### ISSUE TITLE
Question - goog.dom.query alternative

### ISSUE THREAD

**Issue by robfig** [google/closure-library#1094]
We were using goog.dom.query in preference to the native API because it supports :scope on IE11. I see that  goog.dom.query was deleted in 6d144d022e609d5e42e46357bcc9bc9d05945a53. I'm just curious if there's a recommended alternative?

Thanks!

**Comment by shicks** [comment]
You can replace it with `document.querySelectorAll` (or `document.querySelector` or `parentElement.querySelectorAll`, etc).  This is a drop-in replacement that's available in all browsers since ~IE8.  In migrating all of our Google-internal code off of it, I ran into maybe one or two subtle differences (out of thousands of usages), but they weren't too bad to fix once I figured out what was intended (but I don't remember the details, unfortunately).

**Comment by robfig** [comment]
We make use of `:scope`, which is not supported in IE11 via any of the `querySelector` methods. We use it to get elements that are the direct children of the container node, in cases where there might be recursive matches like a multi-level expanding dropdown. 

Was :scope in use around Google, or did you have some workaround that made it unnecessary? I suppose we could add a unique ID to the container so that instead of `> .select-option` it becomes `#new-id > .select-option`. 

Thanks for your thoughts
