### ISSUE TITLE
 Generated API Documentation Missing `goog.async.Throttle`

### ISSUE THREAD

**Issue by drewkutilek** [google/closure-library#1113]
https://github.com/google/closure-library/blob/master/closure/goog/async/throttle.js does not have a page in the generated API documentation @ https://google.github.io/closure-library/api/goog.html#async

It is listed under `goog.Throttle` in the `goog.async` section, but when you click it, you get https://google.github.io/closure-library/api/goog.Throttle.html which results in a 404.

**Comment by 12wrigja** [comment]
Thanks for reporting this. We generate our documentation using the [JsDossier project](https://github.com/jleyba/js-dossier), and it seems that this file is being skipped entirely due to [this line](https://github.com/jleyba/js-dossier/blob/e1d14349dd4d6132b16fef6c56dfe4b33410ca33/src/java/com/github/jsdossier/DocumentableTypePredicate.java#L41) that checks for implicit namespaces (which `goog.async.Throttle` is not, but that conditional does evaluate to true).

I've filed https://github.com/jleyba/js-dossier/issues/120 against the project to get it fixed.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
