### ISSUE TITLE
Wrong placement of negative sign in currency for Norwegian locale

### ISSUE THREAD

**Issue by NorseJedi** [google/closure-library#1124]
I originally reported this as an Angular bug pertaining to the currency pipe, and was told to report it here.

The locale for Norway places the negative sign in front of the symbol rather than in front of the digits.

Negative currency values will currently be formatted like this:
```−kr 1 000,00```

The correct way to format them for Norwegian locale however, is this:
```kr −1 000,00```

**Comment by 12wrigja** [comment]
As the file overview comment indicates, this might be the result of data missing from the CLDR dataset: https://github.com/google/closure-library/blob/39cb429b2e3c12170270b1e92ae2fbaeec007d75/closure/goog/i18n/numberformatsymbols.js#L9

I would guess the correct file to get updated would be https://github.com/unicode-org/cldr/blob/367b79b4a86a9cb12314158897d950268dc77b02/common/main/nb.xml#L11516 but I'd recommend filing a bug against the CLDR data first: http://cldr.unicode.org/index/bug-reports

**Comment by 12wrigja** [comment]
I filed https://unicode-org.atlassian.net/browse/CLDR-14591 to see if this can get fixed upstream.

**Comment by 12wrigja** [comment]
A quick update in case you weren't subscribed to that issue: it seems that this is fixed in CLDR 40. I'm not sure when that will land in Closure Library (that process is managed by a different team at Google).

**Comment by Akisan98** [comment]
Hi If I'm allowed I want to add that Currency should fall behind the numbers: 20 NOK or 20 Kr, instead of in front, like how its handled for French.

**Comment by ensnared** [comment]
> Hi If I'm allowed I want to add that Currency should fall behind the numbers: 20 NOK or 20 Kr, instead of in front, like how its handled for French. "¤ #,##0.00"
> 
> #1157

This is incorrect.

While both placements are allowed both for "NOK" and "kr", the most common placement for "NOK" is in front of the number.
For "kr" it is usually placed after the number when it's part of a written sentence, while in lists and tables and such it can be either (although since MS Excel has always put it in front that's probably the most common placement).

Ref:
Norwegian original: https://www.sprakradet.no/svardatabase/sporsmal-og-svar/kronebelop-rekkjefolgje-komma-og-strek/
English by Google Translate: https://www-sprakradet-no.translate.goog/svardatabase/sporsmal-og-svar/kronebelop-rekkjefolgje-komma-og-strek/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en-US&_x_tr_pto=wapp

**Comment by Akisan98** [comment]
So two Norwegian Devs don't see eye to eye, and I stand corrected; that's because both are valid, so NOK can come before or after amount.

### Språkrådet (The Language Guild)  - https://www.sprakradet.no/svardatabase/sporsmal-og-svar/kronebelop-rekkjefolgje-komma-og-strek/

- The easiest and most natural way is 500 kr (After amount)
- NOK ideally before amount (but can be flipped).
- Normally 500 kr is the best, but in some cases it might be right to flip it.
- If there is multiple currencies then nkr should be used. rather then kr (Considering that Danmark and Sweden also call their currency Kroner)


### So both way should be possible to use in frameworks like Angular (and Flutter?), with Kr / NOK before or after amount as both are valid. 
In Norwegian ",–" is often used to indicate price rather than kr.

If only one can be used then the Facts on Ground is that both Norges Bank and DNB uses Currency after amount.

Norges Bank (The Central Bank) - The institute responsible for monitary policies notes Currency after amount:
https://www.norges-bank.no/tema/Statistikk/Valutakurser/?tab=currency&id=USD

DNB (The National Bank, where Gov. still has 34% share)
https://www.dnb.no/markets/valuta-og-renter/valutakalkulator

**Comment by 12wrigja** [comment]
This might be fixed: https://github.com/google/closure-library/blob/8889f54a9c15153c455d97d3847ad6e827370a6c/closure/goog/i18n/numberformatsymbols.js#L1973

Generally, all this feedback should be reported / debated over in a CLDR ticket, as Closure Library (and Flutter and many many other products) will simply use whatever is specified by CLDR: [cldr.unicode.org/index/bug-reports](https://cldr.unicode.org/index/bug-reports). If the relevant pattern(s) are in CLDR and Closure Library isn't using them, that is definitely something we can address here.

If I'm understanding correctly, the [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) APIs place kr in front of the currency:

```
new Intl.NumberFormat('nb', { style: 'currency', currency: 'NOK' }).format(-1000) //  kr -1.000,00"
```

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
