### ISSUE TITLE
Stop removing functions and breaking your client's code

### ISSUE THREAD

**Issue by beders** [google/closure-library#1128]
Stop deleting functions like `Goog.isArray`. Just forward to `Array.isArray` 
You might end up with a few extra lines of code that are trivial to maintai.

But this will make it much easier for your users to adopt a newer version of this library.

**Comment by 12wrigja** [comment]
In general, it is the position of the Closure Library maintainers that we want to remove the less-useful functions from the library - ones that are clearly no longer needed now that there is a viable cross-browser native implementation. We generally don’t believe that forwarding functions carry their own weight (they increase code size and API surface unnecessarily), and applications are better off cleaning these references up.

For functions in base.js in particular (such as goog.isArray), the standard for a function living in this file is very high as it is used by every single application at Google, and even a single extra function in base.js has a material difference in code size to our end users.

We announced these changes (and all other breaking changes) in our release notes: [deprecation](https://github.com/google/closure-library/releases/tag/v20200315) and [deletion](https://github.com/google/closure-library/releases/tag/v20200628) releases respectively. Every release of Closure Library is a new semver-major version, so these breaking changes should not be unexpected. On major upgrades, we expect users to make the changes necessary to keep our libraries as lean as possible.  When this is necessary, we provide ample warning and give clear guidance on how to do this.

**Comment by beders** [comment]
Breaking your clients’ code for superfluous reasons is bad practice. We adopted your library to not be bothered by browser differences and expected these fns to “just work”. 
Now you put the burden on your users to refactor. Please don’t. 

As a *library* creator you should not break your clients. Of course this library is provided for free and you can do whatever you want 
but we will not adopt any front-end Google library in the future as we can’t rely on it. 

And keeping libraries “as lean as possible” is a bit funny as the closure compiler will remove that code if not used...
That’s the whole point. Justifying removing fns you don’t find useful anymore with code size is showing complete disregard for your users. Especially in base.js 
Would you remove fns from libstdc?

Citing semver as a justification also shows a complete misunderstanding what versioning is about. 
Any change that breaks backward compatibility is *bad*. Hiding it behind a new version number doesn’t make it good.

**Comment by shicks** [comment]
Code size is not the primary concern.  It's the mental overhead of having useless APIs floating around, many of which don't actually work the same as the native ones (even with forwarding aliases in place, Closure Compiler and/or TypeScript often have slightly different type checking behaviors for a variety of reasons).  This leaves us in a place where users don't have a clear understanding of which they should use, ultimately proliferating unnecessary "cargo-cult" dependencies on Closure where native calls would have been fine, and adds extra hurdles to the aggressive telemetry and refactoring we do in our codebase.

I also agree that semver is not a satisfying response.  This is not an ideal situation.  In an ideal world, we would use semver _correctly_ rather than abusing it, and only remove these functions on _real_ major version bumps, which we'd reserve for at most a couple a year.  Unfortunately, this is not particularly compatible with our internal requirements.  Our team's primary responsibility is optimizing the health of Google's entire codebase (i.e. a primarily internal focus), so we aggressively remove uses of obsolete functions throughout the codebase, and deletion is important to prevent backsliding.  Marking functions as "external only" could go part of the way, but then we get problems with API divergence for projects that need to work both internally and externally, as well as test coverage concerns.  So while it's not particularly satisfying, aggressive cleanups is ultimately where we landed.

Generally, the library is mostly "maintenance mode" in that we're not actively developing new features - just cleaning up obsolete ones.  Given that, there's not much in the way of motivation to upgrade the library terribly often - so breaking changes are only a concern on those rare occasions where you actually do need to upgrade.  For what it's worth, other Google frontend frameworks are owned by completely different organizations, many with more external focus than ours, so you'll likely have a very different experience with those.  We're committed to making sure external users are able to keep using Closure in a reasonable way, but we simply don't have the bandwidth to do extra work to minimize churn, particularly when we believe said churn actually makes our users' code base healthier and more readable.
