### ISSUE TITLE
current state

### ISSUE THREAD

**Issue by jt3k** [google/closure-library#1134]
HI.
is this library still alive?

**Comment by kjin** [comment]
Hi @jt3k -- yes, this library is still alive, though it's mostly developed internally within Google.

**Comment by shicks** [comment]
Circling back to this with some more detail, since it's not quite clear what you're asking.

Yes, this library is under active development within Google.  We recognize that the external user base is not particularly large, and growing it is not a priority.  This library meets the needs of many high-requirements products at Google, and we actively respond to issues that come up for them.  We also monitor the GitHub issue tracker, though both internally and externally the majority of our bug fixes are volunteer contributions.  We are not seeking to actively _expand_ the scope of this library, so generally new functionality is added elsewhere.  There is also a significant amount of obsolete content in the library (for instance, goog.ui, goog.structs, and many other packages) that we do not recommend using.  We're working on trimming that down, but much of it is heavily used and difficult to (automatically) migrate away from, so it will likely stick around for a long time.

If you have a more concrete issue, please let us know, but for now I'm closing this issue as unactionable.
