### ISSUE TITLE
Debug loader returns `null` when loading an ES module if `goog.bootstrap` called from a `<script type=module>`

### ISSUE THREAD

**Issue by cpcallen** [google/closure-library#1152]
Consider an ES module using `declareModuleId`:

```JS
goog.declareModuleId('esModule');
export const foo = 'foo';
```

which is required by a `goog.module`:

```JS
goog.module('googModule');
const {foo} = goog.require('esModule');
```

If this is loaded as follows:
```HTML
<html>
  <head>
    <script src="../node_modules/google-closure-library/closure/goog/base.js"></script>
    <script src="deps.js"></script>
    <script>
      goog.bootstrap(['googModule']);
    </script>
  </head>
</html>
```

then all is well.

**If, however, the final `<script>` tag is changed to a `<script type=module>`, then this fails** with
```
Uncaught TypeError: Cannot destructure property 'foo' of 'goog.require(...)' as it is null.
```
…and indeed, this is because `goog.DebugLoader_.prototype.load_` has returned `null`; this appears to be because the `goog.require` call in the dependant module has happened before its dependency has finished loading.

This problem does not occur if the dependant module is converted to also be an ES module:
```JS
goog.declareModuleId('googModule');
const {foo} = goog.require('esModule');
export const bar = 'bar';
```

**Comment by shicks** [comment]
High level response: the person who wrote all this code left Google a while back, and we don't really use ES modules internally at the moment, so this is pretty poorly covered.  Is there a reason the `goog.bootstrap` script needs to be a module?  It sounds like the easiest answer is just "don't do that" - only call `goog.bootstrap` from traditional (non-module) scripts.

Going deeper - I'm stepping through the debug loader and it looks like the difference is that when it's loading the googModule dependency, [`goog.Dependency.defer_`](https://github.com/google/closure-library/blob/23056d424c15d31d45fec6df2c08b7c40b031306/closure/goog/base.js#L3512-L3513) is only `true` when the bootstrap is a script.  For some reason, `defer_` is `false` when called from a module, and thus, `needsAsyncLoading` ends up `false` as well, and the loader tries to load `googModule` synchronously after writing the script tag for `esModule`, but _before_ it's actually loaded.

I've got to step away for a bit, but the next step would be to figure out what's setting `defer_` to true in the one case but failing to in the other.

**Comment by shicks** [comment]
When the esModule is written, there's a check for [`goog.isDocumentLoading_()`](https://github.com/google/closure-library/blob/23056d424c15d31d45fec6df2c08b7c40b031306/closure/goog/base.js#L3311-L3319), and it only sets `defer_ = true` (and uses document.write) if it's currently loading.  When the bootstrap is in a module, the document's no longer loading, so it uses append instead of write and _doesn't_ set defer.  But it's appending a module and the non-deferred googModule load is appending a non-module, so it ends up executing first.

I tried to fix this by also checking if there are any ES modules pending and then setting `defer_` to `true` in that case,  This works for Chrome, but seems to cause a subtle heisenbug in Firefox: normally when loading ES modules, the debug loader adds 4 script (module) tags: a "before" script to set the expectation that an ES module will be loaded, a script with src= to load the file, a script to import and pass the module's exports object back to Closure, and finally an "after" script to clear the ES module expectation.  When not debugging in FF, the "after" module loads _before_ the actual loaded module, so that the loader is no longer expecting an ES module to show up.

This seems like a fundamental issue with Firefox.  The rationale behind using a separate "after" script is that if the loaded module fails to load, we still want to reset the state, so we really do depend on the browser getting the order right here.  Here's a minimal repro to see the problematic Firefox behavior:

```js
// file: a.js
console.log('inside');
```
```html
<script type="module">
function s(src, body) {
  const script = document.createElement('script');
  if (src) script.src = src;
  if (body) script.innerHTML = body;
  script.type = 'module';
  script.defer = true;
  document.head.appendChild(script);
}

s('', `console.log('before');`);
s('a.js');
s('', `console.log('after');`);
</script>
```

In Chrome, this logs (before, inside, after), while in Firefox, it logs (before, after, inside).  I suspect this is a Firefox bug?  I don't understand why this works when the bootstrap command is _not_ in a module (the only difference seems to be the `defer` attribute on the appended script tags - but in my experiment, removing `defer` didn't fix it, nor did even making the main script a non-module).  Given this, I'm at a loss for how to fix it.

**Comment by shicks** [comment]
I see.  Thanks for reporting this, and expanding on what you're doing.

Unfortunately, `goog.bootstrap` is pretty unmaintained, as you may have gathered from the scant documentation.  The short story is that we tried to pivot to ES modules before ultimately settling on TypeScript, and someone on the team at the time rewrote the debug loader (including coming up with `goog.bootstrap`) to handle the combinatorial explosion of dependency types (`goog.provide`, `goog.module`, ES modules) and the various interdependencies between them.  But they left the company years ago and now nobody really understands the debug loader all the well.  With our various renewed efforts to get more users onto bundlers and development servers, we're mostly trying to _turn down_ the debug loader.  Internally, our TypeScript stack doesn't use ES modules, so our well-lit migration path doesn't involve migrating `goog.module`s to ES modules.  (Unfortunately, if you need to build against opensource, there's not much we can do).

Your workaround is indeed kludgy, and I'm sorry that that's what it takes, but as you've gathered, it's unlikely we'll be able to fix this "the right way".  If anybody can figure out how to adjust the debug loader to make it work in all ES-module-supporting browsers, we'd welcome a contribution, but it's not something we're going to be able to prioritize.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
