### ISSUE TITLE
Mark goog.ui as "not for new application" or some sutch.

### ISSUE THREAD

**Issue by bcsgh** [google/closure-library#1186]
According to https://github.com/google/closure-library/issues/1185#issuecomment-1472477618 [`goog.ui`](https://github.com/google/closure-library/tree/master/closure/goog/ui) (at least, maybe other parts of `goog`?) "isn't being maintained anymore." If that's true, then please add something to make that easier to find out.

(If it's not supposed to be true, there are a number of issues that I'd like to file that are causing me trouble.)

**Comment by shicks** [comment]
To reiterate, `goog.ui` is not maintained.  We are planning on making this clearer, but due to some internal constraints, the timeline for this communication is a bit uncertain.  For now, you're much better off considering any of the wide variety of other popular well-maintained UI frameworks that are available today.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
