### ISSUE TITLE
CanvasTextElement cannot construct from CanvasGraphics' .drawText() factory method.

### ISSUE THREAD

**Issue by Datamance** [google/closure-library#408]
Hi!

So, here's the issue:

When you try to call goog.graphics.AbstractGraphics' [.drawText()](https://github.com/google/closure-library/blob/master/closure/goog/graphics/abstractgraphics.js#L341) method from a constructed CanvasGraphics object, the [CanvasTextElement object](https://github.com/google/closure-library/blob/master/closure/goog/graphics/canvasgraphics.js#L534) created by the inner function call to [.drawTextOnLine()] (https://github.com/google/closure-library/blob/master/closure/goog/graphics/abstractgraphics.js#L353) cannot finish constructing because [this.element_](https://github.com/google/closure-library/blob/master/closure/goog/graphics/element.js#L51) (returned by the first method call in [line 533 of canvaselement.js](https://github.com/google/closure-library/blob/master/closure/goog/graphics/canvaselement.js#L533)) is null.

My intuition is that this is an artifact of the graphics package not using goog.base() for superclass constructor calls, but I could be wrong.

Let me know if you need any other information!

**Addendum**
I understand that the goog.graphics package has been "deprecated," but in my mind - WebAPI objects like CanvasRenderingContext2D could really use another abstraction layer for common operations like drawing text starting at a certain point. Perhaps goog.graphics should not be deprecated, but instead *re-purposed as a convenience layer for the now-ubiquitous canvas element*. Also, the package was "deprecated" when I was still at Google over a year ago, and yet it's still getting updates/changes pretty frequently. If the Closure maintainers are truly deprecating an entire namespace, then they should either 1) be 100% consistent with @deprecated JsDoc annotations on the GitHub repo, which (I believe) is what third-party package controls systems like Bower rely on, or 2) remove the package entirely from new versions of the Closure library. If developers wish to use deprecated technology, you can still support them by allowing them to download old versions. But the way it is now - with broken code exposed to the outside world - you run the risk of upsetting users. Just my 2 cents :)

**Comment by Datamance** [comment]
ack- sorry, accidentally submitted before ready - still completing the issue...

**Comment by cmperez** [comment]
:+1:

**Comment by jrrera** [comment]
:+1:

**Comment by joeltine** [comment]
I'm not too familiar with this API, but I took a quick scan. My guess is, it's failing because you didn't create the element via [createDom()](https://github.com/google/closure-library/blob/eb26f425dbd99a70d2955d8fcc892f2fd0178acb/closure/goog/graphics/canvasgraphics.js#L166).

An example:

``` javascript
var graphics = new goog.graphics.CanvasGraphics(100, 100);
graphics.createDom();
graphics.drawText('foo', ...);
...
graphics.render(someElement);
```

BTW, there is a builder method [createGraphics](https://github.com/google/closure-library/blob/master/closure/goog/graphics/graphics.js#L55) that does this for you. It appears to be the standard way to construct these graphics subclasses. 

This API could obviously be much better documented. Also, the fact you can even attempt to draw something with an uninitialized element seems pretty bad. It should at least throw an exception with something like "Did you create the DOM?". Unfortunately, this library is deprecated, and we can't justify spending time on it. However, I would be willing to review straightforward/simple PRs if it helps your project.
