### ISSUE TITLE
goog.dom.forms.getValueByName and input named `item`

### ISSUE THREAD

**Issue by dg** [google/closure-library#449]
`goog.dom.forms.getValueByName()` will not work for inputs named `item` (or `namedItem`), because `form.elements.item` is native function (see http://jsfiddle.net/y4hL2k80/ and [source code](https://github.com/google/closure-library/blob/6e7fe6c9bc0c4785fea72bf631708a01cfb5188d/closure/goog/dom/forms.js#L270))

I am not aware how to fix it, because `form.elements.namedItem(name)` in MSIE will not return collection (`form.elements` in MSIE returns `HtmlCollection` whereas other browsers return [`HtmlFormControlsCollection`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormControlsCollection) and `HtmlFormControlsCollection.namedItem('name')` returns `RadioNodeCollection` containing all inputs, whereas `HtmlCollection.namedItem('name')` returns only the first one).

**Comment by joeltine** [comment]
Ya, an unfortunate side effect of using form.elements. The easy answer to this is "just don't use inputs named 'item'". Given that the fix is likely ugly, we haven't had anyone complain about this internally, and the work around is trivial, it's probably not worth the effort.

What we can do though is fail fast with a meaningful message (e.g., throw when elements returns a non-HTMLCollection or user passes the reserved names) or at the very least add a comment to the method. Just silently returning null now (which I assume is what it does) seems bad.

Feel free to re-open and/or send a PR with either of these and I'll review it.
