### ISSUE TITLE
goog.dom.getDocumentScrollingElement_ will break when WebKit/blink fix their scrollTop bug

### ISSUE THREAD

**Issue by RByers** [google/closure-library#455]
Both [WebKit](wkb.ug/106133) and [Blink](http://crbug.com/157855) are working hard to try to fix their bug where document scrolling is incorrectly controled via body.scrollTop/scrollLeft instead of documentElement.scrollTop.scrollLeft.  Unfortunately Closure relies on a UA check to [expect this bug](https://github.com/google/closure-library/blob/32365aba43acb36c5d693256ef5d4dbe3bddddfe/closure/goog/dom/dom.js#L632) and so fixing the bug in Blink/WebKit [breaks sites using Closure](http://crbug.com/426181).

Ideally Closure would be updated to not rely on a UA check here before we ship this bug fix in Chrome.

Possible solutions:
1. Stop relying on body/documentElement for viewport scrolling (eg. could use window.scrollTo / scrollX / scrollY) instead.  I'm guessing this would be difficult as goog.dom.getDocumentScrollingElement is exposed publicly.
2. Read document scroll position with 'body.scrollTop || documentElement.scrollTop' and write scroll position by setting to body body and documentElement.  Again, the existence of goog.dom.getDocumentScrollingElement may make this difficult.
3. Use a library [like this](https://github.com/mathiasbynens/document.scrollingElement) to test whether document scrolling is on body or documentElement in order to implement getDocumentScrollingElement_ without relying on UA sniffing

Do any of those seem like reasonable options?  We're also considering [shipping a document.scrollingElement API](http://crbug.com/475531) in blink, but that seems a bit like a temporary hack.  What do you think?

**Comment by nanaze** [comment]
Note that doing a heavyweight check as in in solution 3 is a non-starter. Checks at runtime need to be near-free, and code size for checks need to be ~1 statement.

**Comment by nanaze** [comment]
Adding context -- quick chat with @RByers  -- I'd suggested that we just let body and documentElement both control the page, but apparently that's not a route forward since too many sites rely on adding them both in geom calculations.

As stated before -- run time testing of behavior is not going to be OK.

We need to know, in one line, what we're supposed to use to control scrolling. CLosure had done this as a useragent check due to WebKit/Blink's buggy behavior, but the only way I see out of the pickle is to have some browser-exposed API tell us which we should be using so we know, in the lib, . If getScrollingElement existed and gave us the proper scrolling object (whatever is implemented), we would modify the Closure code to use that and eventually drop the userAgent check.

**Comment by joeltine** [comment]
>the only way I see out of the pickle is to have some browser-exposed API tell us which we should be using

Does https://github.com/google/closure-library/commit/5c9bd9e268aae210d96ed6a1d7634f0666b7c844 resolve this?

**Comment by RByers** [comment]
On Thu, Aug 27, 2015 at 1:03 AM, Joel Martinez <notifications@github.com>
wrote:

> the only way I see out of the pickle is to have some browser-exposed API
> tell us which we should be using
>
> Does 5c9bd9e
> <https://github.com/google/closure-library/commit/5c9bd9e268aae210d96ed6a1d7634f0666b7c844>
> resolve this?
>
Yep, that's exactly what we did - shipped document.scrollingElement
<https://drafts.csswg.org/cssom-view/#dom-document-scrollingelement> in
blink and had closure use that if present.
