### ISSUE TITLE
Unusual use of @extends JSDoc tag

### ISSUE THREAD

**Issue by tmcw** [google/closure-library#746]
Hi,

Thanks for the excellent library! I'm using it as a testcase to improve documentation.js's performance on large codebases. One crash I'm running into right now is that [usejsdoc.org](http://usejsdoc.org/tags-augments.html) documents the augments/extends tag like

```js
/**
 * @constructor
 * @extends Animal
 */
```

Whereas closure-library uses it like

```js
/**
 * @constructor
 * @extends {Animal}
 */
```

Is this a mistake on JSDoc's side? Or closure-library's? Or is it part of an extension?

Thanks,

- Tom

**Comment by Dominator008** [comment]
AFAIK Closure does not recognize / use the `@augments` tag. Does it crash Closure Compiler?

**Comment by tmcw** [comment]
Sure - for the purposes of comparison, assume that this is the `@extends` tag, which usejsdoc documents as an alias. I'll update that in the example in this ticket.

**Comment by myphysicslab** [comment]
Closure Compiler started with the JSDoc tags but the two projects have
diverged since then, there is not much relation between them now.  Around
beginning of 2015 I tried to use the JSDoc documentation generator
<http://usejsdoc.org> with my Closure Compiler based code with rather
limited success.  Closure Library is now using Dossier
<https://github.com/jleyba/js-dossier> to generate documentation.  I'm also
using Dossier and it works great.

**Comment by tmcw** [comment]
Thanks @myphysicslab - I'll refer to dossier for understanding closure-library's annotations.
