### ISSUE TITLE
goog.math.long.fromNumber return wrong value

### ISSUE THREAD

**Issue by larest** [google/closure-library#759]
0x8000000000000000 is -9223372036854775808

var lnum=goog.math.long.fromNumber(0x8000000000000000);
 console.log("lnum:",lnum.toString(10));

**show**
_LOG: 'lnum:', '9223372036854775807'_
**incorrect** expect '-9223372036854775808'

 var lstr=goog.math.long.fromString("0x8000000000000000",16);
 console.log("lstr:",lstr.toString(10));
**show**
_LOG: 'lstr:', '-9223372036854775808'_
**correct**

**Comment by mashedcode** [comment]
**That's because you try to play with the negative bit which you shouldn't do in the first place.**
In most ECMAScript engines `0x8000000000000000` is represented as `9223372036854776000` which is the highest positive number and the closure-library explicitly checks against the highest positive number.
Which means that if you provide a number to `fromNumber` which is greater or equal to the highest positive number you'll get the greatest positive number that is representable by 64bits back because it seems like this is what you want and this would be `0x7FFFFFFFFFFFFFFF`.
I don't think anyone would like to get a negative number back if they pass in a positive number.
But you seem to simply want to have the smallest 64 bit number without parsing from string which you can get from `goog.math.Long.getMinValue()` and you can always initialize form two 32 bit numbers to be clear about what you want: `new goog.math.Long(0, -0x80000000)`

We could remove these two lines and your "expected" behavior would occur but I don't think we should do this.
https://github.com/google/closure-library/blob/1f0116d441659b8e3f31c442f58f86adb56d216d/closure/goog/math/long.js#L116

**Comment by larest** [comment]
ok, but I think that I will get same result for fromString("0x8000000000000000",16) and fromNumber(0x8000000000000000)?

**Comment by mashedcode** [comment]
I can see your thought process but even though those two calls look the same to you they're not the same. The string representation is much more accurate where's the representation after IEEE 754 lost accuracy and therefore they're not the same. Especially since you can use much higher numbers in IEEE 754 than you can use when only an int64 is available to you.
So when converting from string a much more accurate decision on what you want can be done where's when you parse from number the decision made should benefit the user and the user most certainly won't expect a positive number turn negative IMHO.
Your example seems very contrived. I can not see an actual application in which you'd want that behavior. The only reason it's a negative number if you parse it from string is that there are not enough bits to represent this number and not because the user would like to have a negative number.
Furthermore by now it's considered bad practice in every language I can think of to calculate the maximum or minimum value by making use of this kind of overflow.
The value is instead usually provided by some constant.
So no IMHO this behavior is justified.
