### ISSUE TITLE
HTML Sanitizer throws error on whitelisted attribute

### ISSUE THREAD

**Issue by KamranAsif** [google/closure-library#764]
Using the HTML Sanitizer, if I attempt to whitelist anchor tags with href attribute, I will get an error saying only whitelisted attributes can be allowed.

```
  var sanitizer = new goog.html.sanitizer.HtmlSanitizer.Builder()
    .onlyAllowTags(['a'])
    .onlyAllowAttributes({tagName: 'a', attributeName: 'href'}) //throws error
    .build();
```

However, if I changed just the line to allow href from any attribute, I won't get any errors
```    .onlyAllowAttributes({tagName: '', attributeName: 'href'})```

I would think that anchor tag href should be included since the wildcard is allowed.
Is this a bug or intended functionality?

**Comment by mashedcode** [comment]
As far as I can tell from the source code it seems like this is intended functionality.

**Comment by rpelizzi** [comment]
The argument to both `onlyAllowAttributes` call is malformed. The method takes an array of {tagName, attributeName, policy} objects, so in your case it would be:

    sanitizer.onlyAllowAttributes([{tagName: 'a', attributeName: 'href'}])

Also the format to register the tag to any handler is` '*'`, not `''`:

    sanitizer.onlyAllowAttributes([{tagName: '*', attributeName: 'href'}])

Note that the second call does not do anything -- whatever attribute handler you provide with your call (in your case, allow all) is chained to the existing one, so that the policy for the handler can only be restricted further, and in your case no restriction happens.

The reason why you can define a handler for '*', 'HREF' and not for 'a', 'HREF' is that the original handler for HREF is defined on '*', not on 'a', and is further refined in the builder's build method to sanitize the url for XSS attacks. Currently you can only define a handler over an existing one, and we don't pipe 'a','href' over to the default '*','href' policy.

By design, the builder in htmlsanitizer.js does not allow specifying unsafe configurations (if you did not pipe the new policy with the existing one, you could override a safe policy with an unsafe one). If you need to loosen the default policy, look into unsafe.js, which adds builder methods to do exactly that. The capabilities of the unsafe module are still pretty limited, I am working on extending it. Stay tuned for (breaking!) changes.

**Comment by KamranAsif** [comment]
Awesome, thanks for the clarification! 
I was using arrays but forgot to wrap it in my example.

[The documentation for onlyAllowAttributes](https://google.github.io/closure-library/api/goog.html.sanitizer.HtmlSanitizer.Builder.html) looks like it didn't esacpe the asterik, so it reads: 

> The tagName can be "", _which means all tags_

Hindsight, I should have double checked the original annotation because it seems a little suspicious.
