### ISSUE TITLE
Object type is not inferred from multimap

### ISSUE THREAD

**Issue by naamaamir** [google/closure-library#771]
Hi,

I have this multimap with callback functions.
When I compile I get "expressions are not callable" error.

Code example:

```js
/** @private {!Multimap<!string,!function(!Match)>} map  */
this.map = new Multimap();
// ....
for (let callback of this.map.get(key)) {
  callback(match);
}
```

The get method returns `Array<*>` instead of `Array<!function(!Match)>`. 
I understand that generics should be used.
I opened this issue to closure-compiler: https://github.com/google/closure-compiler/issues/2151
But I was redirected to the closure-library.

Thanks!

**Comment by shicks** [comment]
The main problem in your code is that `Multimap<function(!Match)>` is nonsense since `Multimap` is not declared with `@template`.  The compiler should probably have a warning for using template paramaters for non-template types (it was impossible when generics were first added since there were so many spurious/incorrect usages, but now that's it's been there for years, this may be feasible).

But Dimitris is right that the "correct" solution would be to add the `@template`.  This should be possible, but `goog.structs` and `goog.labs.structs` are both basically in maintenance mode, since we are working on a cleaner and more coherent collections library.  If you want to try to add the generics and properly type the methods, feel free to send a PR.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
