### ISSUE TITLE
wrong FIRSTDAYOFWEEK in arabic (AR)

### ISSUE THREAD

**Issue by evilaliv3** [google/closure-library#780]
FIRSTDAYOFWEEK of the week for arabic is Sunday (6) (that in arabic means literally first day of the week)

Current codebase declares it as Saturday (5):
https://github.com/google/closure-library/blob/f68f494fd33b4ae7efa8f66701313eb56692fb80/closure/goog/i18n/datetimesymbols.js#L270

**Comment by fabalbon** [comment]
Closure locale data is obtained from [CLDR](http://cldr.unicode.org/) using [ICU](http://site.icu-project.org/). ICU ultimately takes this data from here in CLDR: [common/supplemental/supplementalData.xml/weekData/firstDay](http://unicode.org/cldr/trac/browser/trunk/common/supplemental/supplementalData.xml#L4609)

Even though the "ar" locale doesn't have an explicit territory, in CLDR the implicit territory is "EG" for these types of calculation. And for the "EG" territory the first day of the week is Saturday. Please note that FIRSTDAYOFWEEK is meant to be the first day of the week as shown on a calendar page, not the first working day.

CLDR is the industry standard repository for locale data and we keep Closure in sync with it. If there is any bugs or issues in CLDR data please file a bug here: http://cldr.unicode.org/index/bug-reports . After this bug is fixed this data will be incorporated in Closure on the next locale data update.
