### ISSUE TITLE
assertEquals behaving unexpectedly on goog.math.Long

### ISSUE THREAD

**Issue by keghani** [google/closure-library#783]
I have this test

```nomarkdown
assertEquals(long1, long2);
```

which fails, but this

```nomarkdown
assertTrue(long1.equals(long2));
```

passes.

`long1` and `long2` are of type `goog.math.Long`. Looks to be because assertEquals calls == for all types.
Is this intended?

**Comment by shicks** [comment]
`assertEquals` is not aware of different classes' conception of equivalence.  Calling `==` is "working as intended" in this case, though it would be great if we had a framework that worked better, since `assertTrue` is going to provide a useless failure message.

We're experimenting with what a more modern test assertion framework would look like, and equivalence support is absolutely one of the features we're hoping to target.  For now, I don't think we have much helpful to say in this specific case, though I wouldn't be opposed to adding an `assertLongEquals` method if an appropriate place can be found for it (not sure there is one, though).  But do stay tuned - in the next few quarters we're hoping to have a better answer.

**Comment by nicks** [comment]
i think `assertObjectEquals` is usually better for structural equality? i think it will defer to the equals() method if one exists.

**Comment by keghani** [comment]
Thanks for the explanation!
`assertObjectEquals` does what I need so I'll use it for now.

**Comment by shicks** [comment]
Looks like `assertObjectEquals` does exactly what you want.  Thanks, Nick!
