### ISSUE TITLE
Closure Library in TypeScript

### ISSUE THREAD

**Issue by ayusun** [google/closure-library#789]
Is there any work or chance of development of Closure library in Typescript(typescript definition file).
Closure library with closure compiler works awesome, but there are some problems
1) Way too Verbose(JS Doc based typing)
2) No Intellisense Support.

I believe if typescript is used then
1) Type check will be handled by Typescript
2) Intellisense is already supported in TS so probably, this won't be the issue(well I only believe this part is possible.)

So is there any work going on for this or any plan for this port?

**Comment by mashedcode** [comment]
I assume that you talk about using the closure library in a project that uses TypeScript and for this you'd like to have this TypeScript definition file so that your code completion tool knows what type parameters are and functions return.

In that case:

* I don't get why JSDoc is too verbose since you don't have to write any JSDoc. Furthermore I don't think JSDoc is too verbose since most of it is just the description of each parameter.

* Type checking would be handled by TypeScript if you would call a function from the closure library. That would be the case for your project I guess.

* I don't know this Intellisense code completion tool but my guess would be that Intellisense supports TypeScript and not the other way around. You can probably write an extension for Intellisense so that it supports JSDoc if you wish.

You can write one if you need one and maybe even make a PR.
It doesn't seem useful to anyone who doesn't write a project in TypeScript and would like to use the closure compiler.
You could probably even write a tool that generates one. Have fun!

**Comment by ayusun** [comment]
Hi,
Thanks for the comments.
1) Consider the scenario, you are using closure library to write a web app, in one of the function parameter you have passed a parameter, say list of project, but the whole qualified namespace would be xxx.yyy.zzz.aaa.bbb.project. So our param annotation would be 

`@param {Array.<xxx.yyy.zzz.aaa.bbb.project>}`
using typescript it would be something like
`import {Project} from xxx.yyy.zzz.aaa.bbb` and just use 
`function(param:project){}` and you are good to go and if there are multiple module, we wouldn't need to write so much packages

I just started using closure, so probably it will take me some time(probably a lot), so if some of the older contributors who knows codebase better will probably make it sooner. So, if they probably see it and decide it to be part of next release, probably will make the library a lot easier to use.

**Comment by mashedcode** [comment]
Na you can simplify too:
```
// ==ClosureCompiler==
// @compilation_level ADVANCED_OPTIMIZATIONS
// @output_file_name default.js
// @use_closure_library true
// ==/ClosureCompiler==

goog.module('foo');

const StringBuffer = goog.require('goog.string.StringBuffer');


/**
 * Print the provided buffer.
 * @param {!StringBuffer} buffer
 */
function printBuffer(buffer) {
	console.log(buffer.toString());
}

printBuffer(new StringBuffer('foo', 'bar'));
printBuffer(1);  // This will throw a warning.
```

As far as I understand writing a TypeScript definition file is all about knowing the types and you know them just by looking at the annotations. You don't need to know the codebase for that.

**Comment by shicks** [comment]
As @mashedcode points out, if we rewrote the library in TS then non-TS users would have a harder time using it.  On the other hand, if a `.d.ts` file is sufficient, you might look into [Clutz](https://github.com/angular/clutz), which (as I understand it) extracts `.d.ts` files out of closure-annotated `.js` files.

If you get it working, feel free to contribute any wisdom (in the form of a wiki article or a script, whatever) so that others may benefit from this!

**Comment by mashedcode** [comment]
For further reference note that there's [teppeis/closure-library.d.ts](teppeis/closure-library.d.ts
) generated by [teppeis/closure-ts](https://github.com/teppeis/closure-ts).

**Comment by CoreyCole** [comment]
There are also type definitions in this fork of DefinitelyTyped [fivetran/DefinitelyTyped](https://github.com/fivetran/DefinitelyTyped/tree/master/closure-library).

**Comment by Dan1ve** [comment]
For reference, there now is also a active fork of an up-to-date version of the Closure library that has
- Typescript definition (`.d.ts`) files
- uses ES6 code instead of the custom `goog.require`, `goog.define` etc:

https://github.com/DreierF/ts-closure-library
