### ISSUE TITLE
Functionality to set title of a document

### ISSUE THREAD

**Issue by binarykitchen** [google/closure-library#806]
Looks like such a function to set `<title>` of a HTML document is missing. Or am I wrong?

**Comment by mashedcode** [comment]
What's wrong with `document.title`?

**Comment by binarykitchen** [comment]
ah, right :)

**Comment by JARWATI** [comment]
Pada tanggal 15 Mar 2017 10.52, "Michael Heuberger" <
notifications@github.com> menulis:

ah, right :)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/google/closure-library/issues/806#issuecomment-286625851>,
or mute the thread
