### ISSUE TITLE
Add goog.dom.getElementsByName()

### ISSUE THREAD

**Issue by johnlinp** [google/closure-library#944]
There is `getElementsByClass()` but no `getElementsByName()` in `goog.dom`. I suggest to add `goog.dom.getElementsByName()`.

**Comment by nreid260** [comment]
Hi John!

We appreciate your enthusiasm, but we're currently not interested in adding an more surface to `goog.dom`. Since `goog.dom` was initially written, web standards and cross-platform comparability have improved greatly to the point that it now doesn't serve much purpose. 

We recommend developers just call the native methods directly when writing new code, instead of using `goog.dom` as a trivial wrapper.

**Comment by johnlinp** [comment]
Hi @nreid260,

I see. Thank you for your explanation and suggestions.
