### ISSUE TITLE
Load dependencies after loading

### ISSUE THREAD

**Issue by kwiva** [google/closure-library#994]
Currently it is not possible to load dependencies after the document has loaded. I'm trying to load a module (chunk) on te fly (non compiled). The module requires additional dependencies to be loaded.

This code prevents loading more dependencies after document ready: 
https://github.com/google/closure-library/blob/master/closure/goog/base.js#L3450

The code below the exception is perfectly capable of loading extra dependencies after the document has loaded (not using doc.write but adding to doc.head).

Is the exception still necessary?

**Comment by shicks** [comment]
Strictly speaking, the limitation is not required, but if you look at the comment above, you'll see that it's written as it is because this is not the intended use case.  Basically, `goog.require` is not intended to be used for dynamic loading, so right now failing fast allows detecting that something has gone wrong.

Given that we already have `goog.loader` and `goog.module` for dynamic loading (and the increasing availability of dynamic ES module loading directly in the browser) it makes sense to keep this restriction as it is.  If you want to do late loading, the module manager should provide an existing solution.

**Comment by kwiva** [comment]
Is there public documentation or examples on how to dynamically load modules (or chunks) with Closure (for both unbundled/uncompiled and bundled/compiled)? In the source code I could find a link to internal documentation: [go/js_modules_design](http://go/js_modules_design).

The`goog.addDependency()`, `goog.require()`, `goog.provide()`, and `goog.module()` are strictly bound to `goog.DebugLoader_`. There seems to be no way for `goog.loader` and `goog.module` to load dependencies in an unbundled, uncompiled environment.

One solution would be too copy lots of code from `base.js`, adjust the specified line and implement a custom `DependencyFactory`. That would result in extra duplicated code that needs to be maintained.

**Comment by cpcallen** [comment]
For posterity, [here is the code @kwiva linked to at the top of the issue](https://github.com/google/closure-library/blob/cdcf18cae23416b9fe7d8721fb7652187c40bed9/closure/goog/base.js#L3450) as it was at the time.
